### ISSUE TITLE
ERROR [karma]: [TypeError: Cannot set property 'results' of undefined]

### ISSUE THREAD

**Issue by vignesh1001** [dtabuenc/karma-html-reporter#12]
TypeError: Cannot set property 'results' of undefined
    at onBrowserComplete (C:\Users\434852\Desktop\karma\node_modules\karma-html-reporter\index.js:43:25)
    at null.<anonymous> (C:\Users\434852\Desktop\karma\node_modules\karma\lib\events.js:15:22)

**Comment by dtabuenc** [comment]
This has been fixed in 0.2.6
