### ISSUE TITLE
This reporter causes karma to crash for small errors.

### ISSUE THREAD

**Issue by andrew-luhring** [dtabuenc/karma-html-reporter#13]
Example:

```
INFO [launcher]: Starting browser Chrome
INFO [Chrome 35.0.1916 (Mac OS X 10.8.5)]: Connected on socket EK2rYY15FeDz98z-wxD4 with id 75186479
Chrome 35.0.1916 (Mac OS X 10.8.5) ERROR
  Uncaught Error: Module name "user.controller" has not been loaded yet for context: _
  http://requirejs.org/docs/errors.html#notloaded
  at /Users/user/Sites/project/node_modules/requirejs/require.js:141
ERROR [karma]: [TypeError: Cannot set property 'results' of undefined]
TypeError: Cannot set property 'results' of undefined
    at onBrowserComplete (/Users/user/Sites/project/node_modules/karma-html-reporter/index.js:43:25)
    at null.<anonymous> (/Users/user/Sites/project/node_modules/karma/lib/events.js:15:22)
    at EventEmitter.emit (events.js:117:20)
    at onComplete (/Users/user/Sites/project/node_modules/karma/lib/browser.js:145:13)
    at Socket.<anonymous> (/Users/user/Sites/project/node_modules/karma/lib/events.js:15:22)
    at Socket.EventEmitter.emit [as $emit] (events.js:117:20)
    at SocketNamespace.handlePacket (/Users/user/Sites/project/node_modules/karma/node_modules/socket.io/lib/namespace.js:335:22)
    at Manager.onClientMessage (/Users/user/Sites/project/node_modules/karma/node_modules/socket.io/lib/manager.js:518:38)
    at WebSocket.Transport.onMessage (/Users/user/Sites/project/node_modules/karma/node_modules/socket.io/lib/transport.js:369:20)
    at Parser.<anonymous> (/Users/user/Sites/project/node_modules/karma/node_modules/socket.io/lib/transports/websocket/hybi-16.js:39:10)
```

Also crashes if an extra }, ) function, var f = ; etc.
All small errors.
Karma does not crash if this reporter is disabled.
Just a heads up.

**Comment by dtabuenc** [comment]
This has been fixed in 0.2.6
