### ISSUE TITLE
deprecated write api

### ISSUE THREAD

**Issue by igordezky** [dtabuenc/karma-html-reporter#25]
on node 0.12, latest karma i get this warning when using karma-html-reporter
.write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead.

**Comment by RIAstar** [comment]
This has now become a blocking issue. That API is no longer supported in node 4.x and it now throws.

Here's the stacktrace:

```
TypeError: options must be a string or an object
    at new WriteStream (fs.js:1799:11)
    at Object.fs.createWriteStream (fs.js:1785:10)
    at /home/RIAstar/dev/trasys/seed/angular-app-seed/node_modules/karma-html-reporter/index.js:89:22
    at /home/RIAstar/dev/trasys/seed/angular-app-seed/node_modules/karma/lib/helper.js:82:7
```

**Comment by cheahkhing** [comment]
maybe we should remove the dependency and make it as internal? pretty much screwed if mu2 project no longer maintained and we just stuck here. :(

**Comment by RIAstar** [comment]
Or use [nunjucks](https://github.com/mozilla/nunjucks). Pretty much the de facto standard for template compilation now.

**Comment by OctavioBR** [comment]
+1

**Comment by mattalco** [comment]
Hi everyone, just wondering, is this something that's planned to be fixed in the near future?

**Comment by stevehipwell** [comment]
+1 this is now broken with node 6.

**Comment by agenaille** [comment]
+1 Just upgraded to Node v6.2.0 and this makes my karma tests fail. I had to comment this plugin out for the time being.

**Comment by StevenDevooght** [comment]
+1

**Comment by RIAstar** [comment]
Looks like mu2 finally merged that PR. Guess this can be closed now.
