### ISSUE TITLE
TypeError with io.js v 2.3.0

### ISSUE THREAD

**Issue by bricss** [dtabuenc/karma-html-reporter#26]
```
ERROR [karma]: [TypeError: options must be a string or an object]
TypeError: options must be a string or an object
    at new WriteStream (fs.js:1798:11)
    at Object.fs.createWriteStream (fs.js:1784:10)
    at c:\Users\<username>\Documents\Aptana Studio 3 Workspace\admin-gui\node_modules\karma-html-reporter\index.js:89:22
    at FSReqWrap.oncomplete (fs.js:82:15)
.write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead.
```

**Comment by bricss** [comment]
https://github.com/karma-runner/karma/issues/1454

**Comment by bricss** [comment]
https://github.com/nodejs/io.js/issues/1981

**Comment by bricss** [comment]
Bug raised because of fs.createWriteStream is not support callbacks and should be fixed by using ```error``` and ```close``` events.

**Comment by ChALkeR** [comment]
The callback was ignored before 2.3.0 and started generating an `Error` since 2.3.0.
You should remove it.

https://iojs.org/api/fs.html#fs_fs_createwritestream_path_options
