### ISSUE TITLE
TypeError: Cannot read property 'suites' of undefined

### ISSUE THREAD

**Issue by RLovelett** [dtabuenc/karma-html-reporter#5]
I was trying to test this reporter and when I ran my test suite I got the following error.

```
INFO [reporter.osx]: OSX Notification Center reporter started at http://localhost:1337
INFO [karma]: Karma v0.10.10 server started at http://localhost:9876/
INFO [launcher]: Starting browser Safari
INFO [reporter.osx]: node-osx-notifier exited with code 8
INFO [Safari 7.0.3 (Mac OS X 10.9.2)]: Connected on socket 76zbAucpGbOAabZx085C
Safari 7.0.3 (Mac OS X 10.9.2): Executed 1 of 197 SUCCESS (0 secs / 0.019 secs)
ERROR [karma]: [TypeError: Cannot read property 'suites' of undefined]
TypeError: Cannot read property 'suites' of undefined
  at getOrCreateSuite (/Users/ryan/Source/webview/node_modules/karma-html-reporter/index.js:99:42)
  at [object Object].specSuccess.specSkipped.specFailure (/Users/ryan/Source/webview/node_modules/karma-html-reporter/index.js:85:15)
  at [object Object].onSpecComplete (/Users/ryan/Source/webview/node_modules/karma/lib/reporters/Base.js:80:12)
  at [object Object].EventEmitter.emit (events.js:117:20)
  at [object Object].onResult (/Users/ryan/Source/webview/node_modules/karma/lib/browser.js:177:13)
  at Socket.EventEmitter.emit [as $emit] (events.js:117:20)
  at SocketNamespace.handlePacket (/Users/ryan/Source/webview/node_modules/karma/node_modules/socket.io/lib/namespace.js:335:22)
  at Manager.onClientMessage (/Users/ryan/Source/webview/node_modules/karma/node_modules/socket.io/lib/manager.js:488:38)
  at WebSocket.Transport.onMessage (/Users/ryan/Source/webview/node_modules/karma/node_modules/socket.io/lib/transport.js:387:20)
  at Parser.<anonymous> (/Users/ryan/Source/webview/node_modules/karma/node_modules/socket.io/lib/transports/websocket/hybi-16.js:39:10)
  at Parser.EventEmitter.emit (events.js:95:17)
  at finish (/Users/ryan/Source/webview/node_modules/karma/node_modules/socket.io/lib/transports/websocket/hybi-16.js:288:16)
  at Parser.expectHandler (/Users/ryan/Source/webview/node_modules/karma/node_modules/socket.io/lib/transports/websocket/hybi-16.js:299:15)
  at Parser.add (/Users/ryan/Source/webview/node_modules/karma/node_modules/socket.io/lib/transports/websocket/hybi-16.js:466:24)
  at Parser.expect (/Users/ryan/Source/webview/node_modules/karma/node_modules/socket.io/lib/transports/websocket/hybi-16.js:499:10)
  at Parser.<anonymous> (/Users/ryan/Source/webview/node_modules/karma/node_modules/socket.io/lib/transports/websocket/hybi-16.js:298:18)
  at Parser.add (/Users/ryan/Source/webview/node_modules/karma/node_modules/socket.io/lib/transports/websocket/hybi-16.js:466:24)
  at Parser.expect (/Users/ryan/Source/webview/node_modules/karma/node_modules/socket.io/lib/transports/websocket/hybi-16.js:499:10)
  at expectData (/Users/ryan/Source/webview/node_modules/karma/node_modules/socket.io/lib/transports/websocket/hybi-16.js:296:16)
  at Parser.<anonymous> (/Users/ryan/Source/webview/node_modules/karma/node_modules/socket.io/lib/transports/websocket/hybi-16.js:317:11)
  at Parser.add (/Users/ryan/Source/webview/node_modules/karma/node_modules/socket.io/lib/transports/websocket/hybi-16.js:466:24)
  at Parser.expect (/Users/ryan/Source/webview/node_modules/karma/node_modules/socket.io/lib/transports/websocket/hybi-16.js:499:10)
  at Parser.opcodeHandlers.1 (/Users/ryan/Source/webview/node_modules/karma/node_modules/socket.io/lib/transports/websocket/hybi-16.js:316:14)
  at Parser.processPacket (/Users/ryan/Source/webview/node_modules/karma/node_modules/socket.io/lib/transports/websocket/hybi-16.js:533:8)
  at Parser.add (/Users/ryan/Source/webview/node_modules/karma/node_modules/socket.io/lib/transports/websocket/hybi-16.js:466:24)
  at Socket.<anonymous> (/Users/ryan/Source/webview/node_modules/karma/node_modules/socket.io/lib/transports/websocket/hybi-16.js:141:17)
  at Socket.EventEmitter.emit (events.js:117:20)
  at Socket.<anonymous> (_stream_readable.js:746:14)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:528:21)
```

Help?

**Comment by sajal-n** [comment]
This is happening on my build server when we upgraded to Angular 11. Do we know the exact root cause as this is not consistent but happening very frequently after the upgrade.

ERROR [karma-server]: UncaughtException: TypeError: Cannot read property 'suites' of undefined
    at getOrCreateSuite (/build/ui/node_modules/karma-html-reporter/index.js:137:43)
    at HtmlReporter.specSuccess.specSkipped.specFailure

**Comment by idoodler** [comment]
We also experienced this error on our Buildserver (M1 MacMini)
